/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Bussiness.Facade;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Ricardo
 */
public class AlunosTurno extends javax.swing.JFrame {

    private Facade facade;
    DefaultListModel dm = new DefaultListModel();
    ArrayList<String> array = new ArrayList<String>();
    
    /**
     * Creates new form AlunosTurno
     */
    public AlunosTurno(Facade facade) {
        initComponents();
        this.facade = facade;
        addAlunos();
    }
    
    public void addAlunos(){
        String turno = this.facade.buscaAuxTurno();
        array = this.facade.alunosTurno(turno);
        for(String s : array){
            AlunosList.setModel(dm);
            dm.addElement(s);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SairButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AlunosList = new javax.swing.JList();
        marcarFaltaButton = new javax.swing.JButton();
        registarAvaliacaoButton = new javax.swing.JButton();
        infoButton = new javax.swing.JButton();
        NotaCB = new javax.swing.JComboBox();
        CapacidadeButton = new javax.swing.JButton();
        novaCapacidade = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SairButton.setText("Sair");
        SairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(AlunosList);

        marcarFaltaButton.setText("Marcar falta");
        marcarFaltaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcarFaltaButtonActionPerformed(evt);
            }
        });

        registarAvaliacaoButton.setText("Registar avaliação");
        registarAvaliacaoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registarAvaliacaoButtonActionPerformed(evt);
            }
        });

        infoButton.setText("Informação do aluno");
        infoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoButtonActionPerformed(evt);
            }
        });

        NotaCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        NotaCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotaCBActionPerformed(evt);
            }
        });

        CapacidadeButton.setText("Alterar capacidade");
        CapacidadeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CapacidadeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(marcarFaltaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SairButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(infoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NotaCB, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(registarAvaliacaoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(novaCapacidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CapacidadeButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(marcarFaltaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(registarAvaliacaoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NotaCB, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(infoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CapacidadeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                            .addComponent(novaCapacidade))
                        .addGap(18, 18, 18)
                        .addComponent(SairButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairButtonActionPerformed
        this.dispose();
        LoginDocentes ld = new LoginDocentes(facade);
        ld.setVisible(true);
    }//GEN-LAST:event_SairButtonActionPerformed

    private void marcarFaltaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcarFaltaButtonActionPerformed
        Object sOld = AlunosList.getSelectedValue();
        String aluno = sOld.toString();
        this.facade.marcaFalta(aluno);
    }//GEN-LAST:event_marcarFaltaButtonActionPerformed

    private void infoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoButtonActionPerformed
        Object sOld = AlunosList.getSelectedValue();
        String aluno = sOld.toString();
        int nrFaltas = this.facade.getNrFaltas(aluno);
        int avaliacao = this.facade.getAvaliacao(aluno);
        JOptionPane.showMessageDialog(null, "Nome: " + aluno + "\nNumero de faltas: " + nrFaltas + "\nAvaliação: " + avaliacao);
    }//GEN-LAST:event_infoButtonActionPerformed

    private void registarAvaliacaoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registarAvaliacaoButtonActionPerformed
        Object sOld = AlunosList.getSelectedValue();
        String aluno = sOld.toString();
        Object notaOld = this.NotaCB.getSelectedItem();
        String nota2 = notaOld.toString();
        int nota = Integer.parseInt(nota2);
        this.facade.registarAvaliacao(aluno, nota);
    }//GEN-LAST:event_registarAvaliacaoButtonActionPerformed

    private void NotaCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotaCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NotaCBActionPerformed

    private void CapacidadeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CapacidadeButtonActionPerformed
        Object capacidadeOld = this.novaCapacidade.getText();
        String capacidade2 = capacidadeOld.toString();
        int capacidadeNova = Integer.parseInt(capacidade2);
        this.facade.atualizaCapacidade(capacidadeNova);
    }//GEN-LAST:event_CapacidadeButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList AlunosList;
    private javax.swing.JButton CapacidadeButton;
    private javax.swing.JComboBox NotaCB;
    private javax.swing.JButton SairButton;
    private javax.swing.JButton infoButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton marcarFaltaButton;
    private javax.swing.JTextField novaCapacidade;
    private javax.swing.JButton registarAvaliacaoButton;
    // End of variables declaration//GEN-END:variables
}
