/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Bussiness.Facade;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author André
 */
public class LoginAlunos extends javax.swing.JFrame {
  
    private Facade facade;    
    DefaultListModel dm = new DefaultListModel();
    ArrayList<String> array = new ArrayList<String>();
    /**
     * Creates new form LoginAlunos
     */
    public LoginAlunos(Facade facade) {
        initComponents();
        this.facade = facade;
        add();
    }
    
    public void add(){
        array = this.facade.addUCAluno();
        for(String s : array){
            ItemsText.setModel(dm);
            dm.addElement(s);
        }
    }
              

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ItemsText = new javax.swing.JList<String>();
        AdicionarCadeirasButton = new javax.swing.JButton();
        InfoButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        TrocarTurnosButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        AnularButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(ItemsText);

        AdicionarCadeirasButton.setText("Adicionar Cadeiras");
        AdicionarCadeirasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionarCadeirasButtonActionPerformed(evt);
            }
        });

        InfoButton.setText("Informação");
        InfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        TrocarTurnosButton.setText("Trocar Turnos");
        TrocarTurnosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrocarTurnosButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Ver nr. de alunos num Turno");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        AnularButton.setText("Alunar Inscrição UC");
        AnularButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnularButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(InfoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TrocarTurnosButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AnularButton, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AdicionarCadeirasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InfoButton)
                    .addComponent(AnularButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TrocarTurnosButton)
                    .addComponent(AdicionarCadeirasButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AdicionarCadeirasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionarCadeirasButtonActionPerformed
        this.setVisible(false);
        RegistarUCAluno ru = new RegistarUCAluno(facade);
        ru.setVisible(true);
    }//GEN-LAST:event_AdicionarCadeirasButtonActionPerformed

    private void InfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoButtonActionPerformed
        String s = ItemsText.getSelectedValue();
        String infoTurno = this.facade.infoTurno(s);
        String infoDocente = this.facade.infoDocente(s, infoTurno);
        String infoDocenteResponsavel = this.facade.infoDocenteResponsavel(s, infoTurno);
        String infoSala = this.facade.infoSala(s, infoTurno);
        JOptionPane.showMessageDialog(null, "Turno:  " + infoTurno + "\nDocente:  " + infoDocente + "\nDocente Responsável:  " + infoDocenteResponsavel + "\nSala:  " + infoSala);
    }//GEN-LAST:event_InfoButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        LoginInterface li = new LoginInterface(facade);
        li.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TrocarTurnosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrocarTurnosButtonActionPerformed
        this.setVisible(false);
        TrocarTurnos tt = new TrocarTurnos(facade);
        tt.setVisible(true);
    }//GEN-LAST:event_TrocarTurnosButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        NrAlunosTurno nrat = new NrAlunosTurno(facade);
        nrat.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void AnularButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnularButtonActionPerformed
        String s = ItemsText.getSelectedValue();
        this.facade.anula(s);
        this.dispose();
        JOptionPane.showMessageDialog(null, "Anulou a inscrição à UC: " + s);
        LoginAlunos la = new LoginAlunos(facade);
        la.setVisible(true);
    }//GEN-LAST:event_AnularButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdicionarCadeirasButton;
    private javax.swing.JButton AnularButton;
    private javax.swing.JButton InfoButton;
    private javax.swing.JList<String> ItemsText;
    private javax.swing.JButton TrocarTurnosButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}