/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Bussiness.Aluno;
import Bussiness.Facade;
import Data.AlunoDAO;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author André
 */
public class RegistarUCAluno extends javax.swing.JFrame {
    
    /**
     * Creates new form RegistarUCs
     */
    
    private Facade facade;
    DefaultListModel dmInscritas = new DefaultListModel();
    DefaultListModel dmTodas = new DefaultListModel();
    ArrayList<String> arrayInscritas = new ArrayList<String>();
    ArrayList<String> arrayTodas = new ArrayList<String>();
    
    public RegistarUCAluno(Facade facade) {
        initComponents();
        this.facade = facade;
        completa();
        ListaTodasUC();
    }
    
    public void completa(){
        arrayInscritas = this.facade.addUCAluno();
        for(String s : arrayInscritas){
            ListaInscritos.setModel(dmInscritas);
            dmInscritas.addElement(s);
        }
    }
    
    public void ListaTodasUC(){
        arrayTodas = this.facade.addUCPorInscrever();
        for(String su : arrayTodas){
            ListaUC.setModel(dmTodas);
            dmTodas.addElement(su);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FecharButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaUC = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaInscritos = new javax.swing.JList<>();
        InscreverButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FecharButton.setText("Fechar");
        FecharButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FecharButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(ListaUC);

        jScrollPane2.setViewportView(ListaInscritos);

        InscreverButton.setText("Inscrever");
        InscreverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InscreverButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(344, Short.MAX_VALUE)
                .addComponent(FecharButton)
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InscreverButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(InscreverButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(155, 155, 155)))
                .addGap(22, 22, 22)
                .addComponent(FecharButton)
                .addGap(33, 33, 33))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void FecharButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FecharButtonActionPerformed
        this.setVisible(false);
        LoginAlunos la = new LoginAlunos(facade);
        la.setVisible(true);
    }//GEN-LAST:event_FecharButtonActionPerformed

    private void InscreverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InscreverButtonActionPerformed
        ListaInscritos.setModel(dmInscritas);
        if(this.facade.estaInscrito(ListaUC.getSelectedValue()) == 1){
            JOptionPane.showMessageDialog(null, "ERRO: Já se encontra inscrito a esta Unidade Curricular");
        }
        else{
            this.facade.addTurnos(ListaUC.getSelectedValue());
            dmInscritas.addElement(ListaUC.getSelectedValue());
        }
    }//GEN-LAST:event_InscreverButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FecharButton;
    private javax.swing.JButton InscreverButton;
    private javax.swing.JList<String> ListaInscritos;
    private javax.swing.JList<String> ListaUC;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
