package Presentation;


import Bussiness.Facade;
import Presentation.LoginInterface;
import Presentation.IntroInterface;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author André Vieira
 */
public class RegistarInterface extends javax.swing.JFrame {

    private Facade facade;
    
    public RegistarInterface(Facade facade) {
        initComponents();
        this.facade = facade;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AlunoProfessorButtonGroup = new javax.swing.ButtonGroup();
        RegistarButton = new javax.swing.JButton();
        NomeCompletoLabel = new javax.swing.JLabel();
        UsernameLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        ConfirmarPasswordLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        ConfirmarPasswordField = new javax.swing.JPasswordField();
        NomeCompletoField = new javax.swing.JTextField();
        UsernameField = new javax.swing.JTextField();
        EmailField = new javax.swing.JTextField();
        AlunoButton = new javax.swing.JRadioButton();
        DocenteButton = new javax.swing.JRadioButton();
        VoltarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RegistarButton.setText("Registar");
        RegistarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistarButtonActionPerformed(evt);
            }
        });

        NomeCompletoLabel.setText("Nome Completo");

        UsernameLabel.setText("Username");

        PasswordLabel.setText("Password");

        ConfirmarPasswordLabel.setText("Confirmar Password");

        EmailLabel.setText("Email");

        PasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PasswordFieldKeyPressed(evt);
            }
        });

        ConfirmarPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ConfirmarPasswordFieldKeyPressed(evt);
            }
        });

        NomeCompletoField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NomeCompletoFieldKeyPressed(evt);
            }
        });

        UsernameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UsernameFieldKeyPressed(evt);
            }
        });

        EmailField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EmailFieldKeyPressed(evt);
            }
        });

        AlunoProfessorButtonGroup.add(AlunoButton);
        AlunoButton.setSelected(true);
        AlunoButton.setText("Aluno");
        AlunoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlunoButtonActionPerformed(evt);
            }
        });
        AlunoButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AlunoButtonKeyPressed(evt);
            }
        });

        AlunoProfessorButtonGroup.add(DocenteButton);
        DocenteButton.setText("Docente");
        DocenteButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DocenteButtonKeyPressed(evt);
            }
        });

        VoltarButton.setText("Voltar");
        VoltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(VoltarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RegistarButton)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ConfirmarPasswordLabel)
                    .addComponent(UsernameLabel)
                    .addComponent(EmailLabel)
                    .addComponent(NomeCompletoLabel)
                    .addComponent(PasswordLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AlunoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DocenteButton))
                    .addComponent(PasswordField)
                    .addComponent(ConfirmarPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(NomeCompletoField)
                    .addComponent(UsernameField)
                    .addComponent(EmailField))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeCompletoField)
                    .addComponent(NomeCompletoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernameField)
                    .addComponent(UsernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailField)
                    .addComponent(EmailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordField)
                    .addComponent(PasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConfirmarPasswordField)
                    .addComponent(ConfirmarPasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AlunoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DocenteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(25, 25, 25)
                        .addComponent(RegistarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(VoltarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RegistarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistarButtonActionPerformed
          
          String nome = NomeCompletoField.getText();
          String username = UsernameField.getText();
          String email = EmailField.getText();
          char[] pass = PasswordField.getPassword();
          String password = String.valueOf(pass);
          String tipoUtilizador;
          if(AlunoButton.isSelected()) tipoUtilizador = "Aluno";
          else tipoUtilizador = "Docente";
          
          if(nome .length() > 0 && username.length() > 0 && email.length() > 0 && password.length() > 0 && ConfirmarPasswordField.getText().length() >  0){
              if(username.charAt(0) == 'a' || username.charAt(0) == 'd'){
                  this.facade.registaUtilizador(nome,username,email,password,tipoUtilizador);
                  JOptionPane.showMessageDialog(null, "Registo Feito");
                  this.setVisible(false);
                  LoginInterface li = new LoginInterface(facade);
                  li.setVisible(true);
              }else{
                  JOptionPane.showMessageDialog(null,"Dados Invalidos!");
              }
          }else{
              JOptionPane.showMessageDialog(null,"Verifique se todos os campos estao preenchidos!");
          }
    }//GEN-LAST:event_RegistarButtonActionPerformed

    private void VoltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarButtonActionPerformed
        this.setVisible(false);
        IntroInterface ii = new IntroInterface(facade);
        ii.setVisible(true);
    }//GEN-LAST:event_VoltarButtonActionPerformed

    private void DocenteButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DocenteButtonKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            RegistarButton.doClick();
        }
    }//GEN-LAST:event_DocenteButtonKeyPressed

    private void AlunoButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AlunoButtonKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            RegistarButton.doClick();
        }
    }//GEN-LAST:event_AlunoButtonKeyPressed

    private void AlunoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlunoButtonActionPerformed

    }//GEN-LAST:event_AlunoButtonActionPerformed

    private void EmailFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmailFieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            RegistarButton.doClick();
        }
    }//GEN-LAST:event_EmailFieldKeyPressed

    private void UsernameFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UsernameFieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            RegistarButton.doClick();
        }
    }//GEN-LAST:event_UsernameFieldKeyPressed

    private void NomeCompletoFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NomeCompletoFieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            RegistarButton.doClick();
        }
    }//GEN-LAST:event_NomeCompletoFieldKeyPressed

    private void ConfirmarPasswordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ConfirmarPasswordFieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            RegistarButton.doClick();
        }
    }//GEN-LAST:event_ConfirmarPasswordFieldKeyPressed

    private void PasswordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordFieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            RegistarButton.doClick();
        }
    }//GEN-LAST:event_PasswordFieldKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AlunoButton;
    private javax.swing.ButtonGroup AlunoProfessorButtonGroup;
    private javax.swing.JPasswordField ConfirmarPasswordField;
    private javax.swing.JLabel ConfirmarPasswordLabel;
    private javax.swing.JRadioButton DocenteButton;
    private javax.swing.JTextField EmailField;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JTextField NomeCompletoField;
    private javax.swing.JLabel NomeCompletoLabel;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JButton RegistarButton;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JButton VoltarButton;
    // End of variables declaration//GEN-END:variables
}
