/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Bussiness.Facade;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author André
 */
public class RegistarUCDocente extends javax.swing.JFrame {

    /**
     * Creates new form RegistarUCDocente
     */
    
    private Facade facade;
    DefaultListModel dmInscritasDocente = new DefaultListModel();
    DefaultListModel dmTodasDocente = new DefaultListModel();
    ArrayList<String> arrayInscritasDocente = new ArrayList<String>();
    ArrayList<String> arrayTodasDocente = new ArrayList<String>();
    private int nr = 0;
    
    public RegistarUCDocente(Facade facade) {
        initComponents();
        this.facade = facade;
        completa();
        listaTodasUC();
    }
    
    public void completa(){
        arrayInscritasDocente = this.facade.addUCDocente();
        for(String s : arrayInscritasDocente){
            ListaInscritosDocente.setModel(dmInscritasDocente);
            dmInscritasDocente.addElement(s);
        }
    }
    
    public void listaTodasUC(){
        arrayTodasDocente = this.facade.addUCPorInscreverDocente();
        for(String su : arrayTodasDocente){
            ListaUCDocente.setModel(dmTodasDocente);
            dmTodasDocente.addElement(su);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ListaUCDocente = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaInscritosDocente = new javax.swing.JList<>();
        InscreverButton = new javax.swing.JButton();
        FecharButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(ListaUCDocente);

        jScrollPane2.setViewportView(ListaInscritosDocente);

        InscreverButton.setText("Inscrever");
        InscreverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InscreverButtonActionPerformed(evt);
            }
        });

        FecharButton.setText("Fechar");
        FecharButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FecharButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(344, Short.MAX_VALUE)
                .addComponent(FecharButton)
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InscreverButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(InscreverButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(155, 155, 155)))
                .addGap(22, 22, 22)
                .addComponent(FecharButton)
                .addGap(33, 33, 33))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void InscreverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InscreverButtonActionPerformed

        ListaInscritosDocente.setModel(dmInscritasDocente);
        if(nr < 3){
        this.facade.putRegistaDocente(ListaUCDocente.getSelectedValue());
        dmInscritasDocente.addElement(ListaUCDocente.getSelectedValue());
        nr++;
        }
        else
            JOptionPane.showMessageDialog(null, "Atingiu o número máximo de turnos a lecionar (3)");
    }//GEN-LAST:event_InscreverButtonActionPerformed

    private void FecharButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FecharButtonActionPerformed
        this.setVisible(false);
        LoginDocentes la = new LoginDocentes(facade);
        la.setVisible(true);
    }//GEN-LAST:event_FecharButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FecharButton;
    private javax.swing.JButton InscreverButton;
    private javax.swing.JList<String> ListaInscritosDocente;
    private javax.swing.JList<String> ListaUCDocente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
